### ISSUE TITLE
Run validation as soon as the treebanks are uploaded and print any errors on screen

### ISSUE THREAD

**Issue by harisont** [harisont/STUnD#13]
For instance, if the input isn't valid conllu, the user should know _before_ trying to search. Knowing what format error(s) was/were found without having to look at the log is a nice bonus, particularly useful when grading Computational Syntax assignment or looking at .conllu files in ongoing annotation projects.

**Comment by daherb** [comment]
Implemented in commit https://github.com/harisont/STUnD/commit/bd31c303b2cf7a9592936dbf5eebdd95d02bd2b5
