### ISSUE TITLE
Enable parsing of plain text input

### ISSUE THREAD

**Issue by harisont** [harisont/STUnD#24]
(parsing should only happens once until input files change)

**Comment by harisont** [comment]
I was just thinking that either we add language detection as well (I don't think there is a Haskell library for that but maybe there's a suitable API for that as well) or there has to be a way for the user to decide what language/model to use. In the latter case, I guess a dialog with a text field (is that a thing in the WWW?) is what would clutter the UI the least.

**Comment by daherb** [comment]
> I was just thinking that either we add language detection as well (I don't think there is a Haskell library for that but maybe there's a suitable API for that as well) or there has to be a way for the user to decide what language/model to use. In the latter case, I guess a dialog with a text field (is that a thing in the WWW?) is what would clutter the UI the least.

We could try either this https://github.com/saffsd/langid.js or this https://github.com/Maxacl/Language-Identification

**Comment by harisont** [comment]
Both look like easy-to-use options :100:
