### ISSUE TITLE
Rename and move "highlight discrepancies"

### ISSUE THREAD

**Issue by harisont** [harisont/STUnD#26]
- move to an "options" row so that it isn't confused with modes
- rename to "diff"?

**Comment by daherb** [comment]
See https://github.com/harisont/STUnD/commit/5e7d6f47cff10a0b82d52c7b76b07eeb2c6b52fb and 80ab14f10a5f1b1647d2a07f0fd3f5c635e88a5c

**Comment by harisont** [comment]
cherry picked stuff from branch show-context
